# Generated by Django 4.1.13 on 2024-02-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refcodes",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="invited",
            name="invitee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Приглашенный",
            ),
        ),
        migrations.AddField(
            model_name="invited",
            name="referrer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пригласивший",
            ),
        ),
    ]
