# Generated by Django 4.1.13 on 2024-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invited",
            options={
                "verbose_name": "Пригласивший/Приглашенный",
                "verbose_name_plural": "Пригласившие/Приглашенные",
            },
        ),
        migrations.AddConstraint(
            model_name="invited",
            constraint=models.UniqueConstraint(
                fields=("referrer", "invitee"), name="unique_referrer_invitee"
            ),
        ),
    ]
