# Generated by Django 4.1.13 on 2024-02-07 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0003_alter_invited_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invited",
            name="invitee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Приглашенный",
            ),
        ),
        migrations.AlterField(
            model_name="invited",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пригласивший",
            ),
        ),
    ]
