# Generated by Django 4.1.13 on 2024-02-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailChek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=10)),
                ("result", models.CharField(max_length=10)),
                ("score", models.IntegerField()),
                ("regexp", models.BooleanField()),
                ("gibberish", models.BooleanField()),
                ("disposable", models.BooleanField()),
                ("webmail", models.BooleanField()),
                ("mx_records", models.BooleanField()),
                ("smtp_server", models.BooleanField()),
                ("smtp_check", models.BooleanField()),
                ("accept_all", models.BooleanField()),
                ("block", models.BooleanField()),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
